#!/usr/bin/env bash

version: '2'

services:
  db:
    image: postgres:9.6
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_DB=hasker
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  router:
    image: nginx
    volumes:
     - ./hasker.conf:/etc/nginx/conf.d/default.conf
     - static:/opt/hasker/static
     - logging:/var/log/hasker
    ports:
     - "8000:80"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    links:
     - web

  web:
    image: hasker
    volumes:
     - logging:/var/log/hasker
     - static:/opt/hasker/static
    depends_on:
     - db


volumes:
  pg_data: {}
  pg_backups: {}
  static: {}
  logging: {}
